version: '3'

services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'passwd'
      POSTGRES_DB: 'emistri'

  server:
    build: Dockerfile
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/server
    ports:
      - 3000:3000

  redis:
    image: redis:alpine
    restart: always

volumes:
  postgres_db:
